platform :ios, '10.0'
inhibit_all_warnings!
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'MonoDemo' do
    config = use_native_modules!
    use_react_native!(:path => config["reactNativePath"])
    
end